// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0dfOu1iQtEADM5V35ukCV6u-IQK4ruY8',
    appId: '1:804112151443:web:844bdcc7da44ae443a2e66',
    messagingSenderId: '804112151443',
    projectId: 'bizlinker-b1534',
    authDomain: 'bizlinker-b1534.firebaseapp.com',
    storageBucket: 'bizlinker-b1534.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEBBTKbb_JKro_0KR3ORipzGCgnn_FoIs',
    appId: '1:804112151443:android:e72a7fddd6acba1e3a2e66',
    messagingSenderId: '804112151443',
    projectId: 'bizlinker-b1534',
    storageBucket: 'bizlinker-b1534.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxPtkduD5MZgVFDPlS61MTA9riMtgK9yw',
    appId: '1:804112151443:ios:c3101b243be8e7e53a2e66',
    messagingSenderId: '804112151443',
    projectId: 'bizlinker-b1534',
    storageBucket: 'bizlinker-b1534.firebasestorage.app',
    iosBundleId: 'com.ontrip.itf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxPtkduD5MZgVFDPlS61MTA9riMtgK9yw',
    appId: '1:804112151443:ios:6231fab6fa40478b3a2e66',
    messagingSenderId: '804112151443',
    projectId: 'bizlinker-b1534',
    storageBucket: 'bizlinker-b1534.firebasestorage.app',
    iosBundleId: 'com.example.ontripCustomerFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0dfOu1iQtEADM5V35ukCV6u-IQK4ruY8',
    appId: '1:804112151443:web:52a0454aea90520b3a2e66',
    messagingSenderId: '804112151443',
    projectId: 'bizlinker-b1534',
    authDomain: 'bizlinker-b1534.firebaseapp.com',
    storageBucket: 'bizlinker-b1534.firebasestorage.app',
  );

}