// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAspAqI5M41wLyvAxfV5dQ6_JHmw9dt0vQ',
    appId: '1:618650736687:web:c0f95e70da34ce82a78eda',
    messagingSenderId: '618650736687',
    projectId: 'on-trip-9284c',
    authDomain: 'on-trip-9284c.firebaseapp.com',
    storageBucket: 'on-trip-9284c.firebasestorage.app',
    measurementId: 'G-ESSPC3N9EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnYd4ooCEnpzuPY2qtfa0wyzxFxthv60Y',
    appId: '1:618650736687:android:aa11dcc3af86c98ba78eda',
    messagingSenderId: '618650736687',
    projectId: 'on-trip-9284c',
    storageBucket: 'on-trip-9284c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzkP36d6QqVKdZzLbWPfvQQtpXpszxp-0',
    appId: '1:618650736687:ios:ecae5514cd317ca2a78eda',
    messagingSenderId: '618650736687',
    projectId: 'on-trip-9284c',
    storageBucket: 'on-trip-9284c.firebasestorage.app',
    iosBundleId: 'com.example.ontripCustomerFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzkP36d6QqVKdZzLbWPfvQQtpXpszxp-0',
    appId: '1:618650736687:ios:ecae5514cd317ca2a78eda',
    messagingSenderId: '618650736687',
    projectId: 'on-trip-9284c',
    storageBucket: 'on-trip-9284c.firebasestorage.app',
    iosBundleId: 'com.example.ontripCustomerFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAspAqI5M41wLyvAxfV5dQ6_JHmw9dt0vQ',
    appId: '1:618650736687:web:8429c7a1fad7dc41a78eda',
    messagingSenderId: '618650736687',
    projectId: 'on-trip-9284c',
    authDomain: 'on-trip-9284c.firebaseapp.com',
    storageBucket: 'on-trip-9284c.firebasestorage.app',
    measurementId: 'G-44VQBRMM8W',
  );
}
